#! /bin/sh

#---------------------------------------------------------------------
#                                start                                
# 
# Executed when the package (service) is started up.  
# Not supported by all package formats.
#---------------------------------------------------------------------

exit 0
