#! /bin/sh

#---------------------------------------------------------------------
#                                start                                
# 
# Executed when the package (service) is shut down.
# Not supported by all package formats.
#---------------------------------------------------------------------

exit 0
